name: Runtime Test

on:
  push:
    branches:
      - main
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Production'

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get
        working-directory: ./cli

      - name: Run Runtime tests
        run: dart run test
        working-directory: ./cli
